### ISSUE TITLE
Support for Facebook Login Accounts

### ISSUE THREAD

**Issue by mhoad** [qrpike/spotify-playlist-downloader#1]
Love the idea of this project and would love to have a bit of a play around with it. Just wondering if there was any possible way of finding the appropriate login details for accounts which are linked to Facebook accounts. There doesn't appear to be a username / password associated with the account as far as I can tell??

**Comment by qrpike** [comment]
I believe you may be able to use your facebook login details for spotify as well. I am not 100% sure. I did not connect my facebook account so I cannot check for you. Let me know if you find something that works so I can put it in the readme.

Thanks,

**Comment by mhoad** [comment]
Unfortunately it doesn't appear to work. Thanks for the tip anyways.

**Comment by qrpike** [comment]
A friend of mine was having the same problem. Not really any way around the facebook issue. You have to disconnect your account from FB so spotify assigns you a username & password.

Here are some details on their forums:
https://community.spotify.com/t5/Newcomers-and-Contribution/Tutorial-How-to-Disconnect-Spotify-from-Facebook/td-p/247266
