### ISSUE TITLE
TrackError: Account subscription status not Spotify Premium ...  { Skipping Track }

### ISSUE THREAD

**Issue by rabeetio** [qrpike/spotify-playlist-downloader#16]
I'm getting this error. Has anybody got a workaround for it?

I have got a premium account by the way.

Thanks!

**Comment by leonelfolmer** [comment]
Same thing here, got a premium account too.

**Comment by nerijusgood** [comment]
Here too. Weird, right?

**Comment by nerijusgood** [comment]
Same here - account premium.

**Comment by marcosloic** [comment]
Same

**Comment by oppsig** [comment]
Same

**Comment by qrpike** [comment]
This is a problem with one of the libraries this script uses, you can see the error here: https://github.com/TooTallNate/node-spotify-web/issues/111

**Comment by nerijusgood** [comment]
I saw that too, however there was workaround for that library. It would be nice if this could be updated :+1:

**Comment by qrpike** [comment]
If you link the workaround I will be happy to implement it. Thanks.

*Quinton Pike*
Previously at: *Turner, **CNN, Google* and now at:* TST*
http://qpike.com - and If you must: 404-402-7441

**Comment by leonelfolmer** [comment]
@qrpike, any luck with that?

**Comment by sealskej** [comment]
+1

**Comment by felixhammerl** [comment]
Seems like there are multiple issues at play in in https://github.com/TooTallNate/node-spotify-web/ repo:
- Protocol Buffer Message Types have apparently been updated
- Spotify seems to filter by user agent and plainly throws some out, so you might need to change the user agent to claim it's a current Chrome release
- For some reason, it doesn't work on node@0.12

**Comment by qrpike** [comment]
@felixhammerl Could you create a pull request with the appropriate changes?

**Comment by rabeetio** [comment]
@qrpike Could you update your git with the fix from fuzeman here please? - https://github.com/fuzeman/node-spotify-web/tree/issue/111 :) :) :)

**Comment by qrpike** [comment]
I have updated it to use the forked version. This fixed the account issue.

**Comment by felixhammerl** [comment]
your fix uses the wrong branch for the forked version. please update the package.json accordingly:

```
"spotify-web": "https://github.com/fuzeman/node-spotify-web/tarball/issue/111",
```

**Comment by qrpike** [comment]
Have you tried it? It seems to be working fine for me.

**Comment by felixhammerl** [comment]
no, but
- apparently @rabeetio has concluded that, for magical reasons, it seemed to be working again, w/o your change, which might be what you are experiencing.
- the master branch of the forked repo you linked to in the package.json is in sync with TooTallNate's repo, so there will not be a fix there
- the branch you want to use is [issue/111](https://github.com/fuzeman/node-spotify-web/tree/issue/111), and what i wrote is one way to do this, via https to not run into weird ssh-through-firewall-problems

i just tried the fork in my own little project and it works nicely.

**Comment by qrpike** [comment]
Yea I merged in the issue/111 version and its working fine for me.
