### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by killswitch** [qrpike/spotify-playlist-downloader#2]
When using this app this happens after the first song is downloaded `Error: spawn ENOENT` and if you rerun it again, it says the song was downloaded already, goes to the next one, downloads it and gives this error again.

**Comment by qrpike** [comment]
Can you give me some more details on the issue? OS, Node Version and also please put the entire error log in here ( redact your user account info! ).

**Comment by killswitch** [comment]
OS X Mavericks, v0.10.36

```
$ spotify-playlist-downloader -u **** -p *** -l spotify:user:***:playlist:02l664cS0ZKscWOOk6n2dy
Downloader App Started..
 - Getting Playlist Data
 - Got Playlist: Wintendo
 - Processing 100 Tracks
Already Downlaoded: 8 Bit Weapon GameBoy Rocker
Already Downlaoded: 8 Bit Weapon Sk8 Bit
Already Downlaoded: 8 Bit Weapon Arcade
Already Downlaoded: 8 Bit Weapon Bombs Away!
 - Downloading: 8 Bit Weapon - Panty Raid
 -  - DONE: 8 Bit Weapon - Panty Raid
Error: spawn ENOENT

**Comment by qrpike** [comment]
Seems you don't have ffmpeg installed on your machine. This is the library that writes the ID3 data to the mp3 file ( artist, title, etc. ).

To install: https://trac.ffmpeg.org/wiki/CompilationGuide/MacOSX#ffmpegthroughHomebrew

Let me know if that fixes it for you.

**Comment by killswitch** [comment]
Installing ffmpeg fixed the issue, thank you.
