### ISSUE TITLE
Linux - Error: spawn ENOENT

### ISSUE THREAD

**Issue by LadyVipEx** [qrpike/spotify-playlist-downloader#4]
Downloader App Started..
   Getting Playlist Data
   Got Playlist: Top 100 Hip-Hop Tracks on Spotify
   Processing 100 Tracks
   Already Downlaoded: Drake Energy
   Already Downlaoded: J. Cole Apparently
   Downloading: Usher - I Don't Mind
   DONE: Usher - I Don't Mind
   Error: spawn ENOENT

This happens directly after downloading a song.

Removed Legacy Node JS and installed with nvm.

Now getting same error as 

https://github.com/qrpike/spotify-playlist-downloader/issues/3

**Comment by renalid** [comment]
You need to install FFMPEG. This error is due to the library who add ID3 Tag.

**Comment by LadyVipEx** [comment]
I removed all the "^" before the version in package.json. And changed Coffescript version to 1.9.1

Used Node version v0.11.0.

Then it worked! :)
